FROM registry.access.redhat.com/ubi8/go-toolset AS builder
USER root
WORKDIR /go/src
COPY . .
RUN GOOS=linux make build
FROM registry.access.redhat.com/ubi8/ubi:latest
WORKDIR /
COPY --from=builder /go/src/nodes-ready-app /usr/local/bin/nodes-ready-app
# 65532 is numeric for nonroot
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/nodes-ready-app"]
